jobs:
  IR:
    - 5
    - 10
    - 20
    - 50
    - 100
  QA:
    - 5
    - 10
    - 20
    - 50
    - 100
  TS:
    - 5
    - 10
    - 20
    - 50
    - 100
  RAG:
    - 5
    - 10
    - 20
    - 50
    - 100
  GC:
    - 5
    - 10
    - 20
    - 50
    - 100
  GP:
    - 5
    - 10
    - 20
    - 50
    - 100
